Runner:
  Name: FileSystemWatchingRunner
  Parameters: 
     FolderToWatch: F:\research\Watching\src
Plugins:
- Name: MSBuild
- Name: MSpecTestRunner
  DependsOn: MSBuild
- Name: FileCopy
  DependsOn: MSpecTestRunner
  Parameters: 
    From: F:\research\Watching\src\SAHL.Core\SAHL.Core\bin\Debug
    To: F:\research\Watching\src
Notifications:
- Name: ConsoleNotification
- Name: GrowlNotification