Runner:
  Name: FileSystemWatchingRunner
  Parameters: 
     FolderToWatch: F:\research\Watching\src
Plugins:
- Name: MSBuild
- Name: FileCopy
  DependsOn: MSBuild
  Parameters: 
    From: c:\FromSomeFolder
    To: c:\ToAnotherFolder
Notifications:
- Name: ConsoleNotification
- Name: GrowlNotification