//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jubilee.Console {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class configuration : global::System.Configuration.ApplicationSettingsBase {
        
        private static configuration defaultInstance = ((configuration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new configuration())));
        
        public static configuration Default {
            get {
                return defaultInstance;
            }
        }
    }
}
