Runner:
  Name: FileSystemWatchingRunner
  Parameters: 
     FolderToWatch: c:\FolderToWatch
Tasks:
- Name: BuildingSolution
  Task: MSBuild
- Name: CopyBinaries
  Task: FileCopy 
  DependsOn: BuildingSolution
  Parameters:
    From: c:\FromOneFolder
    To: c:\ToAnotherFolder
Notifications:
- Name: ConsoleNotification
- Name: GrowlNotification