Runner:
  Name: FileSystemWatchingRunner
  Parameters: 
     FolderToWatch: c:\FolderToWatch
Plugins:
- Name: MSBuild
- Name: FileCopy
  DependsOn: MSBuild
  Parameters:
    From: c:\FromOneFolder
    To: c:\ToAnotherFolder
Notifications:
- Name: ConsoleNotification
- Name: GrowlNotification